namespace LoL_Queue_Assistant.Models
{
    public enum AppState
    {
        Disconnected,
        Connected
    }

    public struct Champion
    {
        public string name;
        public int id;

        public Champion(string name, int id)
        {
            this.name = name;
            this.id = id;
        }
    }

    public static class ChampionData
    {
    public static Champion[] champions = {
        new("Aatrox", 266),
        new("Ahri", 103),
        new("Akali", 84),
        new("Akshan", 166),
        new("Alistar", 12),
        new("Ambessa", 799),
        new("Amumu", 32),
        new("Anivia", 34),
        new("Annie", 1),
        new("Aphelios", 523),
        new("Ashe", 22),
        new("Aurelion Sol", 136),
        new("Aurora", 893),
        new("Azir", 268),
        new("Bard", 432),
        new("Bel'Veth", 200),
        new("Blitzcrank", 53),
        new("Brand", 63),
        new("Braum", 201),
        new("Briar", 233),
        new("Caitlyn", 51),
        new("Camille", 164),
        new("Cassiopeia", 69),
        new("Cho'Gath", 31),
        new("Corki", 42),
        new("Darius", 122),
        new("Diana", 131),
        new("Dr. Mundo", 36),
        new("Draven", 119),
        new("Ekko", 245),
        new("Elise", 60),
        new("Evelynn", 28),
        new("Ezreal", 81),
        new("Fiddlesticks", 9),
        new("Fiora", 114),
        new("Fizz", 105),
        new("Galio", 3),
        new("Gangplank", 41),
        new("Garen", 86),
        new("Gnar", 150),
        new("Gragas", 79),
        new("Graves", 104),
        new("Gwen", 887),
        new("Hecarim", 120),
        new("Heimerdinger", 74),
        new("Hwei", 910),
        new("Illaoi", 420),
        new("Irelia", 39),
        new("Ivern", 427),
        new("Janna", 40),
        new("Jarvan IV", 59),
        new("Jax", 24),
        new("Jayce", 126),
        new("Jhin", 202),
        new("Jinx", 222),
        new("Kai'Sa", 145),
        new("Kalista", 429),
        new("Karma", 43),
        new("Karthus", 30),
        new("Kassadin", 38),
        new("Katarina", 55),
        new("Kayle", 10),
        new("Kayn", 141),
        new("Kennen", 85),
        new("Kha'Zix", 121),
        new("Kindred", 203),
        new("Kled", 240),
        new("Kog'Maw", 96),
        new("K'Sante", 897),
        new("LeBlanc", 7),
        new("Lee Sin", 64),
        new("Leona", 89),
        new("Lillia", 876),
        new("Lissandra", 127),
        new("Lucian", 236),
        new("Lulu", 117),
        new("Lux", 99),
        new("Malphite", 54),
        new("Malzahar", 90),
        new("Maokai", 57),
        new("Master Yi", 11),
        new("Mel", 800),
        new("Milio", 902),
        new("Miss Fortune", 21),
        new("Mordekaiser", 82),
        new("Morgana", 25),
        new("Naafiri", 950),
        new("Nami", 267),
        new("Nasus", 75),
        new("Nautilus", 111),
        new("Neeko", 518),
        new("Nidalee", 76),
        new("Nilah", 895),
        new("Nocturne", 56),
        new("Nunu & Willump", 20),
        new("Olaf", 2),
        new("Orianna", 61),
        new("Ornn", 516),
        new("Pantheon", 80),
        new("Poppy", 78),
        new("Pyke", 555),
        new("Qiyana", 246),
        new("Quinn", 133),
        new("Rakan", 497),
        new("Rammus", 33),
        new("Rek'Sai", 421),
        new("Rell", 526),
        new("Renata Glasc", 888),
        new("Renekton", 58),
        new("Rengar", 107),
        new("Riven", 92),
        new("Rumble", 68),
        new("Ryze", 13),
        new("Samira", 360),
        new("Sejuani", 113),
        new("Senna", 235),
        new("Seraphine", 147),
        new("Sett", 875),
        new("Shaco", 35),
        new("Shen", 98),
        new("Shyvana", 102),
        new("Singed", 27),
        new("Sion", 14),
        new("Sivir", 15),
        new("Skarner", 72),
        new("Smolder", 901),
        new("Sona", 37),
        new("Soraka", 16),
        new("Swain", 50),
        new("Sylas", 517),
        new("Syndra", 134),
        new("Tahm Kench", 223),
        new("Taliyah", 163),
        new("Talon", 91),
        new("Taric", 44),
        new("Teemo", 17),
        new("Thresh", 412),
        new("Tristana", 18),
        new("Trundle", 48),
        new("Tryndamere", 23),
        new("Twisted Fate", 4),
        new("Twitch", 29),
        new("Udyr", 77),
        new("Urgot", 6),
        new("Varus", 110),
        new("Vayne", 67),
        new("Veigar", 45),
        new("Vel'Koz", 161),
        new("Vex", 711),
        new("Vi", 254),
        new("Viego", 234),
        new("Viktor", 112),
        new("Vladimir", 8),
        new("Volibear", 106),
        new("Warwick", 19),
        new("Wukong", 62),
        new("Xayah", 498),
        new("Xerath", 101),
        new("Xin Zhao", 5),
        new("Yasuo", 157),
        new("Yone", 777),
        new("Yorick", 83),
        new("Yuumi", 350),
        new("Zac", 154),
        new("Zed", 238),
        new("Zeri", 221),
        new("Ziggs", 115),
        new("Zilean", 26),
        new("Zoe", 142),
        new("Zyra", 143),
    };
    }
}
